services:
  app:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: app-angular
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - todo_app_network
    ports:
      - 4200:4200
    depends_on:
      - api-express
      - db
  api-express:
    build: 
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: todos-api-express
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - todo_app_network
    ports:
      - 3000:3000
    depends_on:
      - db
    command: sh -c "npx prisma migrate dev --name init && npm run dev"
  db:
    image: postgres
    container_name: todo-db
    volumes:
      - postgres_db:/var/lib/postgresql/data
    networks:
      - todo_app_network
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=admin
      - POSTGRES_DB=todo-db

volumes:
  postgres_db:

networks:
  todo_app_network:
