services:
  api-express:
    build: 
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: todos-api-express
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - todo_app_network
    ports:
      - 3001:3000
    depends_on:
      - db
  db:
    image: postgres
    container_name: todo-db
    volumes:
      - postgres_db:/var/lib/postgresql/data
    networks:
      - todo_app_network
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=admin
      - POSTGRES_DB=todo-db

volumes:
  postgres_db:

networks:
  todo_app_network:
